[tool.poetry]
name = "pdf-mint"
version = "0.1.0"
description = ""
authors = ["Brice Fernandes <brice@fractallambda.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
weasyprint = "^62.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
