
services:
  reverse-proxy:
    image: docker.io/traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
    - --api.insecure=true # Don't do this in production
    - --providers.docker
    - --metrics.addinternals=true
    - --accesslog=true
    # - --log.format=json
    - --entryPoints.web.address=:80
    - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"