# permissions for end users to view composedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composedresource-viewer-role
rules:
- apiGroups:
  - meta.fractallambda.com
  resources:
  - composedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meta.fractallambda.com
  resources:
  - composedresources/status
  verbs:
  - get
