# permissions for end users to edit composedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composedresource-editor-role
rules:
- apiGroups:
  - meta.fractallambda.com
  resources:
  - composedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meta.fractallambda.com
  resources:
  - composedresources/status
  verbs:
  - get
